project:
  type: book
  output-dir: docs

book:
  title: "R学习笔记"
  author: "Quan"
  date: today
  date-format: iso
  chapters:
    - index.qmd
    - ch-1.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

